### ISSUE TITLE
Issues with ActiveSupport v 4.1.14

### ISSUE THREAD

**Issue by austinrfnd** [Spokeo/date_time_precision#6]
ActiveSupport line in question:
https://github.com/rails/rails/blob/v4.1.14/activesupport/lib/active_support/core_ext/date_and_time/zones.rb#L36

stacktrace:
```
   ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # /gems/date_time_precision-0.8.0/lib/date_time_precision/lib.rb:178:in `block (3 levels) in included'
     # /gems/activesupport-4.1.14/lib/active_support/core_ext/date_and_time/zones.rb:36:in `time_with_zone'
     # /gems/activesupport-4.1.14/lib/active_support/core_ext/date_and_time/zones.rb:24:in `in_time_zone'
     # /gems/activesupport-4.1.14/lib/active_support/core_ext/date/calculations.rb:66:in `beginning_of_day
```

**Comment by dwbutler** [comment]
Interesting. Didn't know the date/time conversion methods took arguments.
